# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  singularcoffemachine:
    image: singularcoffemachine
    build:
      context: .
      dockerfile: SingularCoffeMachine/Dockerfile
    ports:
      - 5005:5005
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
